apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-mon
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: http

