apiVersion: v1
kind: Pod
metadata:
  name: test-node-selector
  labels: 
    app: test-node-selector
spec:
  containers:
  - image: busybox
    name: test
    command:
    - sleep
    - "3600"
  nodeSelector:
    com: youdianzhishi  # node2
  tolerations:
  - operator: "Exists"
    effect: "NoSchedule"
