apiVersion: v1
kind: Pod
metadata:
  name: pv-hostpath-pod
  namespace: default
spec:
  volumes:
  - name: pv-hostpath
    persistentVolumeClaim:
      claimName: pvc-hostpath
  nodeSelector:
    kubernetes.io/hostname: ydzs-node4
  containers:
  - name: test
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pv-hostpath
      mountPath: "/usr/share/nginx/html"