apiVersion: v1
kind: Pod
metadata:
  name: pv-local-pod
  namespace: default
spec:
  volumes:
  - name: test-pv-local
    persistentVolumeClaim:
      claimName: pvc-local
  containers:
  - name: test
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: test-pv-local
      mountPath: "/usr/share/nginx/html"