apiVersion: v1
kind: Pod
metadata:
  name: test-flexvolume
spec:
  nodeSelector:
    kubernetes.io/hostname: ydzs-node1
  volumes:
  - name: flex
    flexVolume:
      driver: ydzs/nfs
      options:
        server: "10.151.30.11"
        share: "data/k8s"
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
    volumeMounts:
    - name: flex
      subPath: testflexvolume
      mountPath: /usr/share/nginx/html