---
# prometheus-rpm/meta/main.yml

galaxy_info:
  author: Jake Morrison
  description: Install Prometheus packages from RPM
  company: Cogini Hong Kong Limited
  license: Apache 2.0
  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
          - 7
  galaxy_tags:
      - system
      - monitoring
      - prometheus

dependencies: []
